FROM amazonlinux:latest

RUN curl -sL https://rpm.nodesource.com/setup_8.x | bash -
RUN yum install nodejs -y
RUN npm install -g serverless
RUN yum install unzip -y

WORKDIR /tmp/src


CMD ["/bin/bash"]
